const lang = {
  en: {
    search: "Search",
    gptSearchPlaceholder: "What would you like to watch today?",
    emailAddress: "Email Address",
    password: "Password",
    signUp: "Sign Up",
    signOut: "Sign Out",
    signIn: "Sign In",
    loginText: "New to Netflix? Sign up now",
    signUpText: "Already registered? Sign in now.",
    fullName: "Full Name",
    homepage: "HomePage",
    submit: "Submit",
    keyPlaceholder: "Enter your OpenAI key here",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "आज आप क्या देखना पसंद करेंगे?",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    signUp: "साइन अप",
    signOut: "साइन आउट",
    signIn: "साइन इन",
    loginText: "नेटफ्लिक्स में नया है? अब साइन अप करें",
    signUpText: "पहले से ही पंजीकृत? अब साइन इन करो।",
    fullName: "पूरा नाम",
    homepage: "होमपेज",
    submit: "जमा करें",
    keyPlaceholder: "यहां अपनी OpenAI कुंजी दर्ज करें",
  },
  spanish: {
    search: "Buscar",
    gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
    emailAddress: "Dirección de correo electrónico",
    password: "Contraseña",
    signUp: "Inscribirse",
    signOut: "Desconectar",
    signIn: "Iniciar sesión",
    loginText: "¿Nuevo en Netflix? Regístrate ahora",
    signUpText: "¿Ya registrado? Regístrate.",
    fullName: "Nombre completo",
    homepage: "Página de inicio",
    submit: "Enviar",
    keyPlaceholder: "Introduce tu clave de OpenAI aquí",
  },
};

export default lang;
